### PR TITLE
q: does atlantis run on file deletion?

### PR DESCRIPTION
**Pull request by jlm0x013**

### CODE REVIEW

**Comment by atlantislife360** [comment]
Ran Plan for dir: `manifests` workspace: `develop`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_s3_bucket.test-bucket-01 will be destroyed
- resource "aws_s3_bucket" "test-bucket-01" {
      - acl                         = "private" -> null
      - arn                         = "arn:aws:s3:::one-click-jlm-test01" -> null
      - bucket                      = "one-click-jlm-test01" -> null
      - bucket_domain_name          = "one-click-jlm-test01.s3.amazonaws.com" -> null
      - bucket_regional_domain_name = "one-click-jlm-test01.s3.amazonaws.com" -> null
      - force_destroy               = false -> null
      - hosted_zone_id              = "Z3AQBSTGFYJSTF" -> null
      - id                          = "one-click-jlm-test01" -> null
      - region                      = "us-east-1" -> null
      - request_payer               = "BucketOwner" -> null
      - tags                        = {
          - "Environment" = "Dev"
          - "Name"        = "jlm-test-bucket-01"
        } -> null

      - versioning {
          - enabled    = false -> null
          - mfa_delete = false -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d manifests -w develop`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-1click.dev.life360.com/lock?id=life360%252Fone-click-jlm-test01%252Fmanifests%252Fdevelop)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d manifests -w develop`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jlm0x013** [comment]
atlantis apply

**Comment by atlantislife360** [comment]
Ran Apply for dir: `manifests` workspace: `develop`

```diff
aws_s3_bucket.test-bucket-01: Destroying... [id=one-click-jlm-test01]
aws_s3_bucket.test-bucket-01: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

```

**Comment by atlantislife360** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by atlantislife360** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `manifests` workspace: `develop`

**Pull request merged**
