### PR TITLE
test prep - create a bucket.  next: test deletion

### PR DESCRIPTION
**Pull request by jlm0x013**

### CODE REVIEW

**Comment by jlm0x013** [comment]
atlantis plan

**Comment by jlm0x013** [comment]
atlantis plan

**Comment by atlantislife360** [comment]
Ran Plan for dir: `manifests` workspace: `develop`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket.test-bucket-01 will be created
+ resource "aws_s3_bucket" "test-bucket-01" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "one-click-jlm-test01"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Environment" = "Dev"
          + "Name"        = "jlm-test-bucket-01"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d manifests -w develop`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-1click.dev.life360.com/lock?id=life360%252Fone-click-jlm-test01%252Fmanifests%252Fdevelop)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d manifests -w develop`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by jlm0x013** [comment]
atlantis apply

**Comment by atlantislife360** [comment]
Ran Apply for dir: `manifests` workspace: `develop`

```diff
aws_s3_bucket.test-bucket-01: Creating...
aws_s3_bucket.test-bucket-01: Creation complete after 1s [id=one-click-jlm-test01]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by atlantislife360** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by atlantislife360** [comment]
**Warning**: The plan for dir: `manifests` workspace: `develop` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Pull request merged**
